apiVersion: apps/v1 
kind: Deployment
metadata:
  name: usermanagement-deployment
spec:
  selector:
    matchLabels:
      app: maven
  replicas: 2
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: microservice
        image: techouts/fbil-microservice:latest
        ports:
        - containerPort: 81
